# Site settings
title: MLIS Portfolio - Jason M. Seeley
email: jamiseeley@gmail.com
description: >
  This website serves as a record and archive of my e-Portfolio, created as
  my culminating experience for the Master's in Library and Information
  Science from San Jose State University.
baseurl: "/portfolio"
url: "http://jasonseeley.github.io" # the base hostname & protocol for your site
github_username:  jasonseeley

# Build settings
markdown: kramdown
permalink: pretty

kramdown:
  parse_block_html: true

defaults:

  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author: "Jason M. Seeley"
  -
    scope:
      path: "evidence"
      type: "pages"
    values:
      layout: "evidence"
      author: "Jason M. Seeley"

